### PR TITLE
Allow web image to run in arm64

### PR DESCRIPTION
**Pull request by tung2744**
ref #39

### CODE REVIEW

**Comment by Steven-Chan** [comment]
But the base python image is still `linux/amd64` 🤔

**Comment by tung2744** [comment]
:shocked:

You are right.

I just inspected the image in local, and looks like for some reason the architecture of the built image is actually `arm64`. Maybe it is some problem of my local environment. I confirmed the original setup works with a amd64 image.

But what do you think if we just remove the `--platform` argument in Dockerfile so to support building an arm image? (I guess we are all using m1 macbooks?)
Or I will just close this if it is not needed.

@Steven-Chan

**Comment by Steven-Chan** [comment]
@tung2744 Its always good to support multi-platform natively 😸 I also use m1 macbook and I was just lazy to fix it.

**Comment by tung2744** [comment]
Removed platform from base image, thanks

**Pull request merged**
